{"uuid": "d2f3a053-09fa-489c-ad55-a388f61d518f", "children": ["d1cba9fe-bb32-4628-9dfa-8ae5a0f53959"], "befores": [{"name": "flush_browser", "status": "passed", "start": 1609251132619, "stop": 1609251132619}], "afters": [{"name": "flush_browser::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.UnexpectedAlertPresentException: Alert Text: 注册成功,快去登录吧！\nMessage: unexpected alert open: {Alert text : 注册成功,快去登录吧！}\n  (Session info: chrome=87.0.4280.88)\n\n", "trace": "  File \"d:\\programinstall\\python_program\\lib\\site-packages\\allure_commons\\_allure.py\", line 185, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"d:\\programinstall\\python_program\\lib\\site-packages\\_pytest\\fixtures.py\", line 787, in _teardown_yield_fixture\n    next(it)\n  File \"D:\\Python_Script\\UIAutoProject\\project\\demo\\case\\conftest.py\", line 42, in flush_browser\n    getdriver.flush_browser()\n  File \"d:\\programinstall\\python_program\\lib\\site-packages\\lazyTest\\base.py\", line 264, in flush_browser\n    self.base_driver.refresh()\n  File \"d:\\programinstall\\python_program\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 831, in refresh\n    self.execute(Command.REFRESH)\n  File \"d:\\programinstall\\python_program\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"d:\\programinstall\\python_program\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 241, in check_response\n    raise exception_class(message, screen, stacktrace, alert_text)\n"}, "start": 1609251135384, "stop": 1609251135419}], "start": 1609251132619, "stop": 1609251135419}